name: Debug Secrets

on: 
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    environment: Supabase
    
    steps:
      - name: Debug with shell
        run: |
          echo "Shell environment check:"
          echo "SUPABASE_URL exists: ${{ secrets.SUPABASE_URL != '' }}"
          echo "SUPABASE_ANON_KEY exists: ${{ secrets.SUPABASE_ANON_KEY != '' }}"
      
      - name: Debug with Node
        run: |
          cat << EOF > debug.js
          console.log('Node environment check:');
          console.log('SUPABASE_URL:', process.env.SUPABASE_URL ? 'exists' : 'missing');
          console.log('SUPABASE_ANON_KEY:', process.env.SUPABASE_ANON_KEY ? 'exists' : 'missing');
          EOF
          node debug.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
